import React from 'react'
import BarChart from '@/components/gok/barchat';
import PieChart from '@/components/gok/piechart';
import LineChart from '@/components/gok/linechart';
import Topbar from '@/components/gok/topbar';

import data from "@/lib/data.json"
import { Chart as ChartJS, CategoryScale, LinearScale, BarElement, ArcElement, PointElement } from 'chart.js';
ChartJS.register(CategoryScale, LinearScale, BarElement, ArcElement, PointElement);
import SuccesfulDeproyment from '@/components/succesfulDeproyment';


export const metadata = {
    title: "KLES | ADMIN",
    description: "Generated by create next app",
  };

function Admin() {

    const {
        barData1,
        barOptions1,
        pieChartData,
        pieOptions,
        lineChartData,
        lineChartOptions,
        barChartData,
      } = data;

  return (
    <div>
            <div className="sm:ml-64 pb-4  bg-gray-200">
                {/* <img src="/images/image.png" alt="bg" className='w-full h-full absolute object-cover' srcset="" /> */}
                <Topbar/>
                {/* <div className='bg-black opacity-80 absolute w-full h-full'></div> */}
            <div className=" mx-2 mt-14 sm:mt-0 md:mx-4 my-10 py-2 md:p-4 border-2 flex  space-y-2 space-x-0 lg:space-x-2 lg:flex-row flex-col items-center justify-center border-gray-200 border-dashed rounded-lg dark:border-gray-700">
                 <BarChart  data={barChartData} options={barOptions1} title={"Job requested (countries)"}/>
                 {/* <PieChart  data={pieChartData} options={pieOptions} title={"Job Application Stats"}/> */}
            </div>
            <div className="mx-2 md:mx-4 my-10 py-2 md:p-4 border-2  flex  space-y-2 lg:flex-row flex-col border-gray-200 border-dashed rounded-lg dark:border-gray-700">
                 <BarChart  data={barData1} options={barOptions1} title={"Job requested (Categories)"}/>
                 <LineChart  data={lineChartData} options={lineChartOptions} title={"Export Stats"}/>

            </div>
            </div>
    </div>
  )
}

export default Admin

